# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    groups:
      documentation-node-dependencies:
        patterns: ["*"]
  - package-ecosystem: "julia"
    directories:
      # Location of Julia projects
      - "/"
      - "/docs"
      - "/test"
    schedule:
      interval: "weekly"
