steps:
  - label: "Triggering Pipelines (Pull Request)"
    if: build.branch != "main" && build.tag == null
    agents:
      queue: "juliagpu"
    plugins:
      - monebag/monorepo-diff#v2.5.9:
          diff: ".buildkite/scripts/diff.sh $BUILDKITE_COMMIT"
          interpolation: false
          watch:
            - path:
                - "src/"
                - "ext/"
                - "test/"
                - "Project.toml"
                - ".buildkite/"
              config:
                command: "buildkite-agent pipeline upload .buildkite/testing.yml"
                agents:
                  queue: "juliagpu"

  - label: "Triggering Pipelines (Main Branch / Tag)"
    if: build.branch == "main" || build.tag != null
    agents:
      queue: "juliagpu"
    command: "buildkite-agent pipeline upload .buildkite/testing.yml"
