steps:
  - label: ":julia: Julia {{matrix.julia}} + CUDA GPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      BACKEND_GROUP: "CUDA"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 240
    matrix:
      setup:
        julia:
          - "1"

  - label: ":julia: Julia: {{matrix.julia}} + AMD GPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - ext
    env:
      JULIA_AMDGPU_CORE_MUST_LOAD: "1"
      JULIA_AMDGPU_HIP_MUST_LOAD: "1"
      JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
      BACKEND_GROUP: "AMDGPU"
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 240
    matrix:
      setup:
        julia:
          - "1"

env:
  RETESTITEMS_NWORKERS: 4
  RETESTITEMS_NWORKER_THREADS: 2
  SECRET_CODECOV_TOKEN: "TEJEkJA4PvPGNMb6mOizb4+U1eYmEHYk7ojQxLYDQJaarX79BsNs0cmWDOWGj7HkEVYVuQENfUBLqHfv/ih2991s8HS4jHX9zcZhUYXVarWC6Zr+hB8iMReiT7zfoZq7lEocUegTzVEoOstqfFusALwUHibpWHMpaG8SzHD0ii7N53uWyh6HJeQO6mfwusdtgr5oxGgDwYwb1E+iBGGj5AP6z7m+BrXgRbiKaAgoHADYd9AJzhN52S37lkwWMH9RMujFtojyCojIo7f9I5zYoqBKG44uy/IQEoEysf8qQ3WHSBZ/2i+/ircPY4xwVjqS1XZCTbUJ2uHuR+uEETJ9rw==;U2FsdGVkX19yYNkBa1palRpYrA2OylGMaUoLA/TowOS0D2+zxpNW97mOA5vfl13VZSmkQiRElPQEukKTrsFQyA=="
